const log = [
	{
		id: "20250701T102347286-0e5dd6",
		model: {
			"0": "g",
			"1": "p",
			"2": "t",
			"3": "-",
			"4": "4",
			"5": ".",
			"6": "1",
			manual: false,
			cost: 0,
			currency: "USD",
			prices: {
				currency: "USD",
				batchDiscount: 0.5,
				speed: 3,
				input: 2,
				output: 8,
				cache: 0.5,
			},
			features: {
				"0": "t",
				"1": "r",
				"2": "u",
				"3": "e",
				chatCompletions: true,
				assistants: true,
			},
			input: [
				"text",
				"image",
			],
			output: [
				"text",
			],
			context: {
				window: 1047576,
				output: 32768,
				date: "2024-06-01",
				name: "",
				input: 1014808,
			},
			name: "gpt-4.1",
			provider: "",
		},
		prompt: {
			"0": "u",
			"1": "s",
			"2": "e",
			"3": "r",
			role: "user",
			content: "Hello",
			username: "",
		},
		startedAt: 1751365427287,
		chunk: {
			id: "chatcmpl-BoSRSbh7As4hChr2xq9jxdQQoGzgf",
			object: "chat.completion.chunk",
			created: 1751365430,
			model: "gpt-4.1-nano-2025-04-14",
			service_tier: "default",
			system_fingerprint: "fp_38343a2f8f",
			choices: [
				{
					index: 0,
					delta: {
						content: "Hello",
					},
					logprobs: null,
					finish_reason: null,
				},
			],
		},
		delta: "Hello",
		options: {
			model: "gpt-4.1-nano",
			messages: [
				{
					role: "user",
					content: "Hello",
				},
			],
			stream: true,
		},
	},
	{
		id: "20250701T102347286-0e5dd6",
		model: {
			"0": "g",
			"1": "p",
			"2": "t",
			"3": "-",
			"4": "4",
			"5": ".",
			"6": "1",
			manual: false,
			cost: 0,
			currency: "USD",
			prices: {
				currency: "USD",
				batchDiscount: 0.5,
				speed: 3,
				input: 2,
				output: 8,
				cache: 0.5,
			},
			features: {
				"0": "t",
				"1": "r",
				"2": "u",
				"3": "e",
				chatCompletions: true,
				assistants: true,
			},
			input: [
				"text",
				"image",
			],
			output: [
				"text",
			],
			context: {
				window: 1047576,
				output: 32768,
				date: "2024-06-01",
				name: "",
				input: 1014808,
			},
			name: "gpt-4.1",
			provider: "",
		},
		prompt: {
			"0": "u",
			"1": "s",
			"2": "e",
			"3": "r",
			role: "user",
			content: "Hello",
			username: "",
		},
		startedAt: 1751365427287,
		chunk: {
			id: "chatcmpl-BoSRSbh7As4hChr2xq9jxdQQoGzgf",
			object: "chat.completion.chunk",
			created: 1751365430,
			model: "gpt-4.1-nano-2025-04-14",
			service_tier: "default",
			system_fingerprint: "fp_38343a2f8f",
			choices: [
				{
					index: 0,
					delta: {
						content: "!",
					},
					logprobs: null,
					finish_reason: null,
				},
			],
		},
		delta: "!",
		options: {
			model: "gpt-4.1-nano",
			messages: [
				{
					role: "user",
					content: "Hello",
				},
			],
			stream: true,
		},
	},
	{
		id: "20250701T102347286-0e5dd6",
		model: {
			"0": "g",
			"1": "p",
			"2": "t",
			"3": "-",
			"4": "4",
			"5": ".",
			"6": "1",
			manual: false,
			cost: 0,
			currency: "USD",
			prices: {
				currency: "USD",
				batchDiscount: 0.5,
				speed: 3,
				input: 2,
				output: 8,
				cache: 0.5,
			},
			features: {
				"0": "t",
				"1": "r",
				"2": "u",
				"3": "e",
				chatCompletions: true,
				assistants: true,
			},
			input: [
				"text",
				"image",
			],
			output: [
				"text",
			],
			context: {
				window: 1047576,
				output: 32768,
				date: "2024-06-01",
				name: "",
				input: 1014808,
			},
			name: "gpt-4.1",
			provider: "",
		},
		prompt: {
			"0": "u",
			"1": "s",
			"2": "e",
			"3": "r",
			role: "user",
			content: "Hello",
			username: "",
		},
		startedAt: 1751365427287,
		chunk: {
			id: "chatcmpl-BoSRSbh7As4hChr2xq9jxdQQoGzgf",
			object: "chat.completion.chunk",
			created: 1751365430,
			model: "gpt-4.1-nano-2025-04-14",
			service_tier: "default",
			system_fingerprint: "fp_38343a2f8f",
			choices: [
				{
					index: 0,
					delta: {
						content: " How",
					},
					logprobs: null,
					finish_reason: null,
				},
			],
		},
		delta: " How",
		options: {
			model: "gpt-4.1-nano",
			messages: [
				{
					role: "user",
					content: "Hello",
				},
			],
			stream: true,
		},
	},
	{
		id: "20250701T102347286-0e5dd6",
		model: {
			"0": "g",
			"1": "p",
			"2": "t",
			"3": "-",
			"4": "4",
			"5": ".",
			"6": "1",
			manual: false,
			cost: 0,
			currency: "USD",
			prices: {
				currency: "USD",
				batchDiscount: 0.5,
				speed: 3,
				input: 2,
				output: 8,
				cache: 0.5,
			},
			features: {
				"0": "t",
				"1": "r",
				"2": "u",
				"3": "e",
				chatCompletions: true,
				assistants: true,
			},
			input: [
				"text",
				"image",
			],
			output: [
				"text",
			],
			context: {
				window: 1047576,
				output: 32768,
				date: "2024-06-01",
				name: "",
				input: 1014808,
			},
			name: "gpt-4.1",
			provider: "",
		},
		prompt: {
			"0": "u",
			"1": "s",
			"2": "e",
			"3": "r",
			role: "user",
			content: "Hello",
			username: "",
		},
		startedAt: 1751365427287,
		chunk: {
			id: "chatcmpl-BoSRSbh7As4hChr2xq9jxdQQoGzgf",
			object: "chat.completion.chunk",
			created: 1751365430,
			model: "gpt-4.1-nano-2025-04-14",
			service_tier: "default",
			system_fingerprint: "fp_38343a2f8f",
			choices: [
				{
					index: 0,
					delta: {
						content: " can",
					},
					logprobs: null,
					finish_reason: null,
				},
			],
		},
		delta: " can",
		options: {
			model: "gpt-4.1-nano",
			messages: [
				{
					role: "user",
					content: "Hello",
				},
			],
			stream: true,
		},
	},
	{
		id: "20250701T102347286-0e5dd6",
		model: {
			"0": "g",
			"1": "p",
			"2": "t",
			"3": "-",
			"4": "4",
			"5": ".",
			"6": "1",
			manual: false,
			cost: 0,
			currency: "USD",
			prices: {
				currency: "USD",
				batchDiscount: 0.5,
				speed: 3,
				input: 2,
				output: 8,
				cache: 0.5,
			},
			features: {
				"0": "t",
				"1": "r",
				"2": "u",
				"3": "e",
				chatCompletions: true,
				assistants: true,
			},
			input: [
				"text",
				"image",
			],
			output: [
				"text",
			],
			context: {
				window: 1047576,
				output: 32768,
				date: "2024-06-01",
				name: "",
				input: 1014808,
			},
			name: "gpt-4.1",
			provider: "",
		},
		prompt: {
			"0": "u",
			"1": "s",
			"2": "e",
			"3": "r",
			role: "user",
			content: "Hello",
			username: "",
		},
		startedAt: 1751365427287,
		chunk: {
			id: "chatcmpl-BoSRSbh7As4hChr2xq9jxdQQoGzgf",
			object: "chat.completion.chunk",
			created: 1751365430,
			model: "gpt-4.1-nano-2025-04-14",
			service_tier: "default",
			system_fingerprint: "fp_38343a2f8f",
			choices: [
				{
					index: 0,
					delta: {
						content: " I",
					},
					logprobs: null,
					finish_reason: null,
				},
			],
		},
		delta: " I",
		options: {
			model: "gpt-4.1-nano",
			messages: [
				{
					role: "user",
					content: "Hello",
				},
			],
			stream: true,
		},
	},
	{
		id: "20250701T102347286-0e5dd6",
		model: {
			"0": "g",
			"1": "p",
			"2": "t",
			"3": "-",
			"4": "4",
			"5": ".",
			"6": "1",
			manual: false,
			cost: 0,
			currency: "USD",
			prices: {
				currency: "USD",
				batchDiscount: 0.5,
				speed: 3,
				input: 2,
				output: 8,
				cache: 0.5,
			},
			features: {
				"0": "t",
				"1": "r",
				"2": "u",
				"3": "e",
				chatCompletions: true,
				assistants: true,
			},
			input: [
				"text",
				"image",
			],
			output: [
				"text",
			],
			context: {
				window: 1047576,
				output: 32768,
				date: "2024-06-01",
				name: "",
				input: 1014808,
			},
			name: "gpt-4.1",
			provider: "",
		},
		prompt: {
			"0": "u",
			"1": "s",
			"2": "e",
			"3": "r",
			role: "user",
			content: "Hello",
			username: "",
		},
		startedAt: 1751365427287,
		chunk: {
			id: "chatcmpl-BoSRSbh7As4hChr2xq9jxdQQoGzgf",
			object: "chat.completion.chunk",
			created: 1751365430,
			model: "gpt-4.1-nano-2025-04-14",
			service_tier: "default",
			system_fingerprint: "fp_38343a2f8f",
			choices: [
				{
					index: 0,
					delta: {
						content: " assist",
					},
					logprobs: null,
					finish_reason: null,
				},
			],
		},
		delta: " assist",
		options: {
			model: "gpt-4.1-nano",
			messages: [
				{
					role: "user",
					content: "Hello",
				},
			],
			stream: true,
		},
	},
	{
		id: "20250701T102347286-0e5dd6",
		model: {
			"0": "g",
			"1": "p",
			"2": "t",
			"3": "-",
			"4": "4",
			"5": ".",
			"6": "1",
			manual: false,
			cost: 0,
			currency: "USD",
			prices: {
				currency: "USD",
				batchDiscount: 0.5,
				speed: 3,
				input: 2,
				output: 8,
				cache: 0.5,
			},
			features: {
				"0": "t",
				"1": "r",
				"2": "u",
				"3": "e",
				chatCompletions: true,
				assistants: true,
			},
			input: [
				"text",
				"image",
			],
			output: [
				"text",
			],
			context: {
				window: 1047576,
				output: 32768,
				date: "2024-06-01",
				name: "",
				input: 1014808,
			},
			name: "gpt-4.1",
			provider: "",
		},
		prompt: {
			"0": "u",
			"1": "s",
			"2": "e",
			"3": "r",
			role: "user",
			content: "Hello",
			username: "",
		},
		startedAt: 1751365427287,
		chunk: {
			id: "chatcmpl-BoSRSbh7As4hChr2xq9jxdQQoGzgf",
			object: "chat.completion.chunk",
			created: 1751365430,
			model: "gpt-4.1-nano-2025-04-14",
			service_tier: "default",
			system_fingerprint: "fp_38343a2f8f",
			choices: [
				{
					index: 0,
					delta: {
						content: " you",
					},
					logprobs: null,
					finish_reason: null,
				},
			],
		},
		delta: " you",
		options: {
			model: "gpt-4.1-nano",
			messages: [
				{
					role: "user",
					content: "Hello",
				},
			],
			stream: true,
		},
	},
	{
		id: "20250701T102347286-0e5dd6",
		model: {
			"0": "g",
			"1": "p",
			"2": "t",
			"3": "-",
			"4": "4",
			"5": ".",
			"6": "1",
			manual: false,
			cost: 0,
			currency: "USD",
			prices: {
				currency: "USD",
				batchDiscount: 0.5,
				speed: 3,
				input: 2,
				output: 8,
				cache: 0.5,
			},
			features: {
				"0": "t",
				"1": "r",
				"2": "u",
				"3": "e",
				chatCompletions: true,
				assistants: true,
			},
			input: [
				"text",
				"image",
			],
			output: [
				"text",
			],
			context: {
				window: 1047576,
				output: 32768,
				date: "2024-06-01",
				name: "",
				input: 1014808,
			},
			name: "gpt-4.1",
			provider: "",
		},
		prompt: {
			"0": "u",
			"1": "s",
			"2": "e",
			"3": "r",
			role: "user",
			content: "Hello",
			username: "",
		},
		startedAt: 1751365427287,
		chunk: {
			id: "chatcmpl-BoSRSbh7As4hChr2xq9jxdQQoGzgf",
			object: "chat.completion.chunk",
			created: 1751365430,
			model: "gpt-4.1-nano-2025-04-14",
			service_tier: "default",
			system_fingerprint: "fp_38343a2f8f",
			choices: [
				{
					index: 0,
					delta: {
						content: " today",
					},
					logprobs: null,
					finish_reason: null,
				},
			],
		},
		delta: " today",
		options: {
			model: "gpt-4.1-nano",
			messages: [
				{
					role: "user",
					content: "Hello",
				},
			],
			stream: true,
		},
	},
	{
		id: "20250701T102347286-0e5dd6",
		model: {
			"0": "g",
			"1": "p",
			"2": "t",
			"3": "-",
			"4": "4",
			"5": ".",
			"6": "1",
			manual: false,
			cost: 0,
			currency: "USD",
			prices: {
				currency: "USD",
				batchDiscount: 0.5,
				speed: 3,
				input: 2,
				output: 8,
				cache: 0.5,
			},
			features: {
				"0": "t",
				"1": "r",
				"2": "u",
				"3": "e",
				chatCompletions: true,
				assistants: true,
			},
			input: [
				"text",
				"image",
			],
			output: [
				"text",
			],
			context: {
				window: 1047576,
				output: 32768,
				date: "2024-06-01",
				name: "",
				input: 1014808,
			},
			name: "gpt-4.1",
			provider: "",
		},
		prompt: {
			"0": "u",
			"1": "s",
			"2": "e",
			"3": "r",
			role: "user",
			content: "Hello",
			username: "",
		},
		startedAt: 1751365427287,
		chunk: {
			id: "chatcmpl-BoSRSbh7As4hChr2xq9jxdQQoGzgf",
			object: "chat.completion.chunk",
			created: 1751365430,
			model: "gpt-4.1-nano-2025-04-14",
			service_tier: "default",
			system_fingerprint: "fp_38343a2f8f",
			choices: [
				{
					index: 0,
					delta: {
						content: "?",
					},
					logprobs: null,
					finish_reason: null,
				},
			],
		},
		delta: "?",
		options: {
			model: "gpt-4.1-nano",
			messages: [
				{
					role: "user",
					content: "Hello",
				},
			],
			stream: true,
		},
	},
	{
		id: "20250701T102347286-0e5dd6",
		model: {
			"0": "g",
			"1": "p",
			"2": "t",
			"3": "-",
			"4": "4",
			"5": ".",
			"6": "1",
			manual: false,
			cost: 0,
			currency: "USD",
			prices: {
				currency: "USD",
				batchDiscount: 0.5,
				speed: 3,
				input: 2,
				output: 8,
				cache: 0.5,
			},
			features: {
				"0": "t",
				"1": "r",
				"2": "u",
				"3": "e",
				chatCompletions: true,
				assistants: true,
			},
			input: [
				"text",
				"image",
			],
			output: [
				"text",
			],
			context: {
				window: 1047576,
				output: 32768,
				date: "2024-06-01",
				name: "",
				input: 1014808,
			},
			name: "gpt-4.1",
			provider: "",
		},
		prompt: {
			"0": "u",
			"1": "s",
			"2": "e",
			"3": "r",
			role: "user",
			content: "Hello",
			username: "",
		},
		startedAt: 1751365427287,
		options: {
			model: "gpt-4.1-nano",
			messages: [
				{
					role: "user",
					content: "Hello",
				},
			],
			stream: true,
		},
		content: "Hello! How can I assist you today?",
	},
]

const chunks = log.map((el) => el.chunk)
console.log(chunks.length)

import ChatEventData from "./EventData.js"

const events = log.map(ChatEventData.from)
console.log(events)
